spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  profiles:
    active: dev
  messages:
    basename: i18n/messages

comment.avatar: /images/avatar.jpeg